package com.zw.website.model.product;

public class KindStatistics {

    public KindStatistics() {

    }

    public KindStatistics(String province, Integer kindCnt) {
        this.province = province;
        this.kindCnt = kindCnt;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind_statistics.province
     *
     * @mbggenerated Sat Sep 24 20:16:11 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind_statistics.kind_cnt
     *
     * @mbggenerated Sat Sep 24 20:16:11 CST 2016
     */
    private Integer kindCnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind_statistics.province
     *
     * @return the value of kind_statistics.province
     *
     * @mbggenerated Sat Sep 24 20:16:11 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind_statistics.province
     *
     * @param province the value for kind_statistics.province
     *
     * @mbggenerated Sat Sep 24 20:16:11 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind_statistics.kind_cnt
     *
     * @return the value of kind_statistics.kind_cnt
     *
     * @mbggenerated Sat Sep 24 20:16:11 CST 2016
     */
    public Integer getKindCnt() {
        return kindCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind_statistics.kind_cnt
     *
     * @param kindCnt the value for kind_statistics.kind_cnt
     *
     * @mbggenerated Sat Sep 24 20:16:11 CST 2016
     */
    public void setKindCnt(Integer kindCnt) {
        this.kindCnt = kindCnt;
    }
}