package com.zw.website.model.car;

public class BrandEngineFuel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_engine_fuel.brand
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_engine_fuel.engine
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private String engine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_engine_fuel.fuel
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private String fuel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_engine_fuel.amount
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_engine_fuel.brand
     *
     * @return the value of brand_engine_fuel.brand
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_engine_fuel.brand
     *
     * @param brand the value for brand_engine_fuel.brand
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_engine_fuel.engine
     *
     * @return the value of brand_engine_fuel.engine
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_engine_fuel.engine
     *
     * @param engine the value for brand_engine_fuel.engine
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setEngine(String engine) {
        this.engine = engine == null ? null : engine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_engine_fuel.fuel
     *
     * @return the value of brand_engine_fuel.fuel
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public String getFuel() {
        return fuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_engine_fuel.fuel
     *
     * @param fuel the value for brand_engine_fuel.fuel
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setFuel(String fuel) {
        this.fuel = fuel == null ? null : fuel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_engine_fuel.amount
     *
     * @return the value of brand_engine_fuel.amount
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_engine_fuel.amount
     *
     * @param amount the value for brand_engine_fuel.amount
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}