package com.zw.website.model.car;

public class CarsSaleScaleByMonth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars_sale_scale_by_month.month
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars_sale_scale_by_month.scale
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private String scale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars_sale_scale_by_month.month
     *
     * @return the value of cars_sale_scale_by_month.month
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars_sale_scale_by_month.month
     *
     * @param month the value for cars_sale_scale_by_month.month
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars_sale_scale_by_month.scale
     *
     * @return the value of cars_sale_scale_by_month.scale
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars_sale_scale_by_month.scale
     *
     * @param scale the value for cars_sale_scale_by_month.scale
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }
}