package com.zw.website.model.car;

public class CarsUsageAmountDist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars_usage_amount_dist.usages
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private String usages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars_usage_amount_dist.city
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars_usage_amount_dist.amount
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars_usage_amount_dist.usages
     *
     * @return the value of cars_usage_amount_dist.usages
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public String getUsages() {
        return usages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars_usage_amount_dist.usages
     *
     * @param usages the value for cars_usage_amount_dist.usages
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setUsages(String usages) {
        this.usages = usages == null ? null : usages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars_usage_amount_dist.city
     *
     * @return the value of cars_usage_amount_dist.city
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars_usage_amount_dist.city
     *
     * @param city the value for cars_usage_amount_dist.city
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars_usage_amount_dist.amount
     *
     * @return the value of cars_usage_amount_dist.amount
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars_usage_amount_dist.amount
     *
     * @param amount the value for cars_usage_amount_dist.amount
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}