package com.zw.website.model.car;

public class CityDistrictSaleDist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_district_sale_dist.province
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_district_sale_dist.city
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_district_sale_dist.district
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_district_sale_dist.amount
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_district_sale_dist.province
     *
     * @return the value of city_district_sale_dist.province
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_district_sale_dist.province
     *
     * @param province the value for city_district_sale_dist.province
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_district_sale_dist.city
     *
     * @return the value of city_district_sale_dist.city
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_district_sale_dist.city
     *
     * @param city the value for city_district_sale_dist.city
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_district_sale_dist.district
     *
     * @return the value of city_district_sale_dist.district
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_district_sale_dist.district
     *
     * @param district the value for city_district_sale_dist.district
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_district_sale_dist.amount
     *
     * @return the value of city_district_sale_dist.amount
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_district_sale_dist.amount
     *
     * @param amount the value for city_district_sale_dist.amount
     *
     * @mbggenerated Mon Sep 26 17:53:24 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}