package com.zw.website.model.car;

public class GenderScale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gender_scale.gender
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gender_scale.scale
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    private String scale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gender_scale.gender
     *
     * @return the value of gender_scale.gender
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gender_scale.gender
     *
     * @param gender the value for gender_scale.gender
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gender_scale.scale
     *
     * @return the value of gender_scale.scale
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gender_scale.scale
     *
     * @param scale the value for gender_scale.scale
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }
}