package com.zw.website.dao.car.impl;

import com.zw.framework.dao.AbstractDao;
import com.zw.website.dao.car.CarsUsageAmountDistMapper;
import com.zw.website.model.car.CarsUsageAmountDist;
import com.zw.website.model.car.CarsUsageAmountDistExample;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Created by zhangws on 16/9/24.
 */
@Repository
public class CarsUsageAmountDistMapperImpl extends AbstractDao implements CarsUsageAmountDistMapper {

    private static final String NAMESPACE = "com.zw.website.dao.car.CarsUsageAmountDistMapper";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars_usage_amount_dist
     *
     * @param example
     *
     * @mbggenerated Sat Sep 24 19:34:11 CST 2016
     */
    @Override
    public List<CarsUsageAmountDist> selectByExample(CarsUsageAmountDistExample example) {
        return this.getSqlSession().selectList(NAMESPACE + ".selectByExample", example);
    }
}
