package com.zw.website.dao.car.impl;

import com.zw.framework.dao.AbstractDao;
import com.zw.website.dao.car.CarsSaleScaleByMonthMapper;
import com.zw.website.model.car.CarsSaleScaleByMonth;
import com.zw.website.model.car.CarsSaleScaleByMonthExample;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Created by zhangws on 16/9/24.
 */
@Repository
public class CarsSaleScaleByMonthMapperImpl extends AbstractDao implements CarsSaleScaleByMonthMapper {

    private static final String NAMESPACE = "com.zw.website.dao.car.CarsSaleScaleByMonthMapper";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars_sale_scale_by_month
     *
     * @param example
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    @Override
    public List<CarsSaleScaleByMonth> selectByExample(CarsSaleScaleByMonthExample example) {
        return this.getSqlSession().selectList(NAMESPACE + ".selectByExample");
    }
}
