package com.zw.website.dao.car.impl;

import com.zw.framework.dao.AbstractDao;
import com.zw.website.dao.car.CityDistrictSaleDistMapper;
import com.zw.website.model.car.CityDistrictSaleDist;
import com.zw.website.model.car.CityDistrictSaleDistExample;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Created by zhangws on 16/9/24.
 */
@Repository
public class CityDistrictSaleDistMapperImpl extends AbstractDao implements CityDistrictSaleDistMapper {

    private static final String NAMESPACE = "com.zw.website.dao.car.CityDistrictSaleDistMapper";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_district_sale_dist
     *
     * @param example
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    @Override
    public List<CityDistrictSaleDist> selectByExample(CityDistrictSaleDistExample example) {
        return this.getSqlSession().selectList(NAMESPACE + ".selectByExample");
    }

    @Override
    public List<CityDistrictSaleDist> selectProvince(CityDistrictSaleDistExample example) {
        return this.getSqlSession().selectList(NAMESPACE + ".selectProvince", example);
    }

    @Override
    public List<CityDistrictSaleDist> selectCity(CityDistrictSaleDistExample example) {
        return this.getSqlSession().selectList(NAMESPACE + ".selectCity", example);
    }
}
