package com.zw.website.dao.car.impl;

import com.zw.framework.dao.AbstractDao;
import com.zw.website.dao.car.OwnerTypeBrandMapper;
import com.zw.website.model.car.OwnerTypeBrand;
import com.zw.website.model.car.OwnerTypeBrandExample;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Created by zhangws on 16/9/24.
 */
@Repository
public class OwnerTypeBrandMapperImpl extends AbstractDao implements OwnerTypeBrandMapper {

    private static final String NAMESPACE = "com.zw.website.dao.car.OwnerTypeBrandMapper";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner_type_brand
     *
     * @param example
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    @Override
    public List<OwnerTypeBrand> selectByExample(OwnerTypeBrandExample example) {
        return this.getSqlSession().selectList(NAMESPACE + ".selectByExample", example);
    }
}
