package com.zw.website.model;

public class CoKindModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_kind.kind
     *
     * @mbggenerated Fri Sep 23 15:05:57 CST 2016
     */
    private String kind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_kind.kind
     *
     * @return the value of co_kind.kind
     *
     * @mbggenerated Fri Sep 23 15:05:57 CST 2016
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_kind.kind
     *
     * @param kind the value for co_kind.kind
     *
     * @mbggenerated Fri Sep 23 15:05:57 CST 2016
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }
}