package com.zw.website.model;

import java.util.ArrayList;
import java.util.List;

public class KindStatisticsModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public KindStatisticsModelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andKindCntIsNull() {
            addCriterion("kind_cnt is null");
            return (Criteria) this;
        }

        public Criteria andKindCntIsNotNull() {
            addCriterion("kind_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andKindCntEqualTo(Integer value) {
            addCriterion("kind_cnt =", value, "kindCnt");
            return (Criteria) this;
        }

        public Criteria andKindCntNotEqualTo(Integer value) {
            addCriterion("kind_cnt <>", value, "kindCnt");
            return (Criteria) this;
        }

        public Criteria andKindCntGreaterThan(Integer value) {
            addCriterion("kind_cnt >", value, "kindCnt");
            return (Criteria) this;
        }

        public Criteria andKindCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("kind_cnt >=", value, "kindCnt");
            return (Criteria) this;
        }

        public Criteria andKindCntLessThan(Integer value) {
            addCriterion("kind_cnt <", value, "kindCnt");
            return (Criteria) this;
        }

        public Criteria andKindCntLessThanOrEqualTo(Integer value) {
            addCriterion("kind_cnt <=", value, "kindCnt");
            return (Criteria) this;
        }

        public Criteria andKindCntIn(List<Integer> values) {
            addCriterion("kind_cnt in", values, "kindCnt");
            return (Criteria) this;
        }

        public Criteria andKindCntNotIn(List<Integer> values) {
            addCriterion("kind_cnt not in", values, "kindCnt");
            return (Criteria) this;
        }

        public Criteria andKindCntBetween(Integer value1, Integer value2) {
            addCriterion("kind_cnt between", value1, value2, "kindCnt");
            return (Criteria) this;
        }

        public Criteria andKindCntNotBetween(Integer value1, Integer value2) {
            addCriterion("kind_cnt not between", value1, value2, "kindCnt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kind_statistics
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 23 14:39:15 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}