package com.zw.website.model;

public class MarketStatisticsModel {

    public MarketStatisticsModel() {

    }

    public MarketStatisticsModel(String province, Integer marketCnt) {
        this.province = province;
        this.marketCnt = marketCnt;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_statistics.province
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_statistics.market_cnt
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    private Integer marketCnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_statistics.province
     *
     * @return the value of market_statistics.province
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_statistics.province
     *
     * @param province the value for market_statistics.province
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_statistics.market_cnt
     *
     * @return the value of market_statistics.market_cnt
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public Integer getMarketCnt() {
        return marketCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_statistics.market_cnt
     *
     * @param marketCnt the value for market_statistics.market_cnt
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void setMarketCnt(Integer marketCnt) {
        this.marketCnt = marketCnt;
    }
}