package com.zw.website.model;

import java.util.Date;

public class PriceStatisticsModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_statistics.kind
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_statistics.collect_date
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    private Date collectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_statistics.price
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_statistics.kind
     *
     * @return the value of price_statistics.kind
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_statistics.kind
     *
     * @param kind the value for price_statistics.kind
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_statistics.collect_date
     *
     * @return the value of price_statistics.collect_date
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public Date getCollectDate() {
        return collectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_statistics.collect_date
     *
     * @param collectDate the value for price_statistics.collect_date
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void setCollectDate(Date collectDate) {
        this.collectDate = collectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_statistics.price
     *
     * @return the value of price_statistics.price
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_statistics.price
     *
     * @param price the value for price_statistics.price
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void setPrice(Float price) {
        this.price = price;
    }
}