package com.zw.website.model;

public class ProvinceModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.name
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.name
     *
     * @return the value of province.name
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.name
     *
     * @param name the value for province.name
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}