package com.zw.website.dao.product.impl;

import com.zw.framework.dao.AbstractDao;
import com.zw.website.dao.product.KindStatisticsMapper;
import com.zw.website.model.product.KindStatistics;
import com.zw.website.model.product.KindStatisticsExample;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Created by zhangws on 16/9/22.
 */
@Repository
public class KindStatisticsMapperImpl extends AbstractDao implements KindStatisticsMapper {

    private static final String NAMESPACE = "com.zw.website.dao.product.KindStatisticsMapper";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_statistics
     *
     * @param example
     *
     * @mbggenerated Thu Sep 22 21:21:00 CST 2016
     */
    @Override
    public List<KindStatistics> selectByExample(KindStatisticsExample example) {
        return this.getSqlSession().selectList(NAMESPACE + ".selectByExample");
    }
}
