package com.zw.website.dao.car;

import com.zw.website.model.car.BrandEngineFuel;
import com.zw.website.model.car.BrandEngineFuelExample;
import java.util.List;

public interface BrandEngineFuelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_engine_fuel
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    List<BrandEngineFuel> selectByExample(BrandEngineFuelExample example);
}