package com.zw.website.dao.car;

import com.zw.website.model.car.CarsSaleScaleByMonth;
import com.zw.website.model.car.CarsSaleScaleByMonthExample;
import java.util.List;

public interface CarsSaleScaleByMonthMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars_sale_scale_by_month
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    List<CarsSaleScaleByMonth> selectByExample(CarsSaleScaleByMonthExample example);
}