package com.zw.website.dao.car;

import com.zw.website.model.car.CarsUsageAmountDist;
import com.zw.website.model.car.CarsUsageAmountDistExample;
import java.util.List;

public interface CarsUsageAmountDistMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars_usage_amount_dist
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    List<CarsUsageAmountDist> selectByExample(CarsUsageAmountDistExample example);
}