package com.zw.website.dao.car;

import com.zw.website.model.car.DiffBrandMonthSaleDist;
import com.zw.website.model.car.DiffBrandMonthSaleDistExample;
import java.util.List;

public interface DiffBrandMonthSaleDistMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diff_brand_month_sale_dist
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    List<DiffBrandMonthSaleDist> selectByExample(DiffBrandMonthSaleDistExample example);

    List<String> selectBrand();
}