package com.zw.website.dao.car;

import com.zw.website.model.car.OwnerTypeBrand;
import com.zw.website.model.car.OwnerTypeBrandExample;
import java.util.List;

public interface OwnerTypeBrandMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner_type_brand
     *
     * @mbggenerated Sat Sep 24 20:17:02 CST 2016
     */
    List<OwnerTypeBrand> selectByExample(OwnerTypeBrandExample example);
}