package com.zw.website.dao.product;

import com.zw.website.model.CoKindModel;
import com.zw.website.model.CoKindModelExample;
import java.util.List;

public interface CoKindModelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_kind
     *
     * @mbggenerated Fri Sep 23 15:05:57 CST 2016
     */
    List<CoKindModel> selectByExample(CoKindModelExample example);
}