package com.zw.website.dao.product;

import com.zw.website.model.KindStatisticsModel;
import com.zw.website.model.KindStatisticsModelExample;

import java.util.List;

public interface KindStatisticsModelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    List<KindStatisticsModel> selectByExample(KindStatisticsModelExample example);
}