package com.zw.website.dao.product;

import com.zw.website.model.MarketStatisticsModel;
import com.zw.website.model.MarketStatisticsModelExample;
import java.util.List;

public interface MarketStatisticsModelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    List<MarketStatisticsModel> selectByExample(MarketStatisticsModelExample example);
}