package com.zw.website.dao.product;

import com.zw.website.model.product.MarketStatistics;
import com.zw.website.model.product.MarketStatisticsExample;

import java.util.List;

public interface MarketStatisticsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_statistics
     *
     * @mbggenerated Sat Sep 24 19:39:57 CST 2016
     */
    List<MarketStatistics> selectByExample(MarketStatisticsExample example);
}