package com.zw.website.dao.product;

import com.zw.website.model.PriceStatisticsModel;
import com.zw.website.model.PriceStatisticsModelExample;
import java.util.List;

public interface PriceStatisticsModelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_statistics
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    List<PriceStatisticsModel> selectByExample(PriceStatisticsModelExample example);
}