package com.zw.website.dao.product;

import com.zw.website.model.product.PriceStatistics;
import com.zw.website.model.product.PriceStatisticsExample;

import java.util.List;

public interface PriceStatisticsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_statistics
     *
     * @mbggenerated Sat Sep 24 19:39:57 CST 2016
     */
    List<PriceStatistics> selectByExample(PriceStatisticsExample example);
}