package com.zw.website.dao.product;

import com.zw.website.model.ProvinceModel;
import com.zw.website.model.ProvinceModelExample;
import java.util.List;

public interface ProvinceModelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Fri Sep 23 14:39:15 CST 2016
     */
    List<ProvinceModel> selectByExample(ProvinceModelExample example);
}